### ISSUE TITLE
provider/v3 unable to read prior state

### ISSUE THREAD

**Issue by utahcon** [hashicorp/terraform-provider-helm#1574]
### Terraform, Provider, Kubernetes and Helm Versions
```
Terraform version: 1.10.5
Provider version: 3.0.0-pre1
Kubernetes version: 1.32 (eks.2)
```

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "karpenter" {
  chart      = "karpenter"
  name       = "karpenter"
  namespace  = "kube-system"
  version    = "1.1.2"
  repository = "oci://public.ecr.aws/karpenter"

  values = [
    templatefile("${path.module}/karpenter/values.yaml", {
      CLUSTER_NAME       = local.cluster.name
      KARPENTER_ROLE_ARN = data.terraform_remote_state.eks.outputs.karpenter.role.arn
    })
  ]

  wait = true

  timeout = 60
}
```

### Debug Output
https://gist.githubusercontent.com/utahcon/2e12436524c7b79e65cc98cd85248aa3/raw/d20e9016cabe95a4cf61f56776d66baf63eb9794/tfp.log

### Steps to Reproduce
1. Change from helm provider `2.17.0` to `3.0.0-pre1`
2. `terraform init --upgrade`
3. Updated `kubernetes` configuration object, and `set` parameters for `helm_release`
4. `terraform plan`

### Expected Behavior
Terraform is expected to pull the previous state, parse the files, and then compare the new configuration for changes.

### Actual Behavior
Terraform and the Helm provider are unable to parse the existing state using the new provider

```hcl
╷
│ Warning: Failed to decode resource from state
│ 
│ Error decoding "helm_release.karpenter" from prior state: missing expected {
╵
╷
│ Error: Unable to Read Previously Saved State for UpgradeResourceState
│ 
│   with helm_release.karpenter,
│   on karpenter.tf line 45, in resource "helm_release" "karpenter":
│   45: resource "helm_release" "karpenter" {
│ 
│ There was an error reading the saved resource state using the current resource schema.
│ 
│ If this resource state was last refreshed with Terraform CLI 0.11 and earlier, it must be refreshed or applied with an older provider version first. If you manually modified the resource state, you will need to manually modify it to
│ match the current resource schema. Otherwise, please report this to the provider developer:
│ 
│ AttributeName("metadata"): invalid JSON, expected "{", got "["
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by hulakv** [comment]
Have the same issue. Any updates?

**Comment by LifeMoroz** [comment]
The same problem with 
Provider version: 3.0.0-pre2

**Comment by rosmo** [comment]
Saw this error too - looks like there are no `StateUpgrader`s in the v3, so I'm not sure if it's meant to preserve backwards compatibility or not.

**Comment by lae** [comment]
For this issue in particular, the `metadata` field happens to be a list in v2 and was retyped into an object/map in v3. Attributes for the most part appear to be the same, except v3 seems to have removed the `notes` attribute. 

https://github.com/hashicorp/terraform-provider-helm/blob/65288321af862811a08cea2817bc8cd655ba76ce/helm/resource_helm_release.go#L348-L389

Without investigating any further I'm assuming in v2 `metadata` was always a single item list (looking at our own environment's state file with several helm releases, all I saw were single item lists), so it wasn't necessary to use a list...in that case, adding a `StateUpgrader` should be okay, right?

**Comment by lae** [comment]
`postrender` appears to be another affected attribute that went through the same type change.

Anyway I tried to manually modify these in the state, minimally, but ran into a crash (still as a result of upgrading the helm provider with existing releases so I'm keeping it in this thread) that seems to be happening elsewhere... https://gist.github.com/lae/e08f6df9851a7f92ca05591a53db980c

**Comment by jaylonmcshan19-x** [comment]
The bug has been resolved with this PR #1633 .
Thank you for creating the issue @utahcon :)

**Comment by dima-sh-papaya** [comment]
getting the same error with 3.0.2 provider version, after updating my configs according to changelog, and running init with '-upgrade' so it'll use the latest provider (I verified the lock file had 3.0.2 at that moment). are there any additional steps for some state migration or it was supposed to run correctly? not sure where to look for the reason of that error, if it is considered solved in that version of provider, should i pull the state and modify anything manually?

**Comment by cgsyam** [comment]
I am trying to upgrade provider version from `3.0.0-pre2` to `3.0.2` and facing the same issue.

**Comment by hfinger** [comment]
We have the same issue when upgrading from `3.0.0-pre2` to `3.0.2`

**Comment by cgsyam** [comment]
@jaylonmcshan19-x Could you please help? From comments, it seems like many are still facing same issue when upgrading from `3.0.0-pre2` to `3.0.2`

**Comment by mattmarich-wrstbnd** [comment]
Experiencing the same issue upgrading from `3.0.0-pre2` to `3.0.2`

**Comment by vebu42** [comment]
helm v3.0.2 same issue

**Comment by cgsyam** [comment]
For anyone having issues upgrading from `3.0.0-pre2` to `3.0.2`, changing `"schema_version": 1` to `"schema_version": 2` directly on the state file and then changing provider to `3.0.2` worked for me. Please make sure you test and validate yourself before making any critical changes.

**Comment by WeetA34** [comment]
Hello,
I initially ignored the message from @cgsyam due to the thumb down.
So, I compared helm_release resource data from 3.0.0-pre2 and 3.0.2 states.
I arrived to the exact same conclusion. No difference except schema_version.
I updated schema_version from 1 to 2 and it worked
