### ISSUE TITLE
istio-init chart recreating CRD on each terraform apply

### ISSUE THREAD

**Issue by jindalarpit** [hashicorp/terraform-provider-helm#345]
### Terraform Version
0.12.9

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "istio_init" {
  name       = "istio_init"
  repository = "istio.io"
  chart      = "istio-init"
  version    = "1.1.8"
  namespace  = "istio-system"
}
```

### Debug Output
```hcl
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
Terraform will perform the following actions:
  # helm_release.istio_init will be created
  + resource "helm_release" "istio_init" {
      + chart            = "istio-init"
      + disable_webhooks = false
      + force_update     = false
      + id               = (known after apply)
      + metadata         = (known after apply)
      + name             = "istio_init"
      + namespace        = "istio-system"
      + recreate_pods    = false
      + repository       = "istio.io"
      + reuse            = false
      + reuse_values     = false
      + status           = "DEPLOYED"
      + timeout          = 300
      + verify           = false
      + version          = "1.1.8"
      + wait             = true
    }
Plan: 1 to add, 0 to change, 0 to destroy.
```

### Expected Behavior
Istio-init helm chart creates the CRDs for Istio installation. It should run only once during first execution of `terraform apply`. 
From second time onward it should skip CRD creation if `terraform.tfstate` already contains the resource information.

### Actual Behavior
Resource is re-created every time when `terraform apply` is executed. 

### Steps to Reproduce
1. `terraform apply`

**Comment by MattyKuzyk** [comment]
Possibly unrelated, but have you run into any issues installing the `istio` chart through Terraform after `istio-init`? I implemented a custom provisioner so that `istio` waits until the CRDs from `istio-init` are ready before it is applied.

However, I receive an error saying that there are no matches for the CRD (e.g `DestinationRule`).

Wondering if this issue is related.

**Comment by cowlingj** [comment]
@MattyKuzyk it sounds to me like your `istio-init` CRDs aren't actually getting applied, so kubernetes has no idea what a `DestinationRule` is

**Comment by ghost** [comment]
This also happens for other charts as well.

**Comment by ghost** [comment]
The problem was solved by removing underscores from a resource name.

**Comment by venky999** [comment]
I am still seeing this kind of issue for other charts.. my resource don't have underscores

**Comment by aareet** [comment]
@alexander-klang @venky999 can you share which other charts this was reproducible for? Also, can you provide us with a debug log by setting TF_LOG=TRACE? 

https://www.terraform.io/docs/internals/debugging.html

**Comment by aareet** [comment]
I'm going to close this since it has been 21 days since the request for additional info to help us reproduce. Please reopen if this is still an issue.

**Comment by ismailyenigul** [comment]
I have the same issue with https://github.com/lablabs/terraform-aws-eks-alb-ingress chart

**Comment by ismailyenigul** [comment]
here is the terraform plan ouput
```

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place
 <= read (data resources)

Terraform will perform the following actions:

  # module.eksalbingress.data.aws_iam_policy_document.alb_ingress[0] will be read during apply
  # (config refers to values not yet known)
 <= data "aws_iam_policy_document" "alb_ingress"  {
      + id   = (known after apply)
      + json = (known after apply)

      + statement {
          + actions   = [
              + "acm:DescribeCertificate",
              + "acm:GetCertificate",
              + "acm:ListCertificates",
            ]
          + effect    = "Allow"
          + resources = [
              + "*",
            ]
        }
      + statement {
          + actions   = [
              + "ec2:AuthorizeSecurityGroupIngress",
              + "ec2:CreateSecurityGroup",
              + "ec2:CreateTags",
              + "ec2:DeleteSecurityGroup",
              + "ec2:DeleteTags",
              + "ec2:DescribeAccountAttributes",
              + "ec2:DescribeAddresses",
              + "ec2:DescribeInstanceStatus",
              + "ec2:DescribeInstances",
              + "ec2:DescribeInternetGateways",
              + "ec2:DescribeNetworkInterfaces",
              + "ec2:DescribeSecurityGroups",
              + "ec2:DescribeSubnets",
              + "ec2:DescribeTags",
              + "ec2:DescribeVpcs",
              + "ec2:ModifyInstanceAttribute",
              + "ec2:ModifyNetworkInterfaceAttribute",
              + "ec2:RevokeSecurityGroupIngress",
            ]
          + effect    = "Allow"
          + resources = [
              + "*",
            ]
        }
      + statement {
          + actions   = [
              + "elasticloadbalancing:AddListenerCertificates",
              + "elasticloadbalancing:AddTags",
              + "elasticloadbalancing:CreateListener",
              + "elasticloadbalancing:CreateLoadBalancer",
              + "elasticloadbalancing:CreateRule",
              + "elasticloadbalancing:CreateTargetGroup",
              + "elasticloadbalancing:DeleteListener",
              + "elasticloadbalancing:DeleteLoadBalancer",
              + "elasticloadbalancing:DeleteRule",
              + "elasticloadbalancing:DeleteTargetGroup",
              + "elasticloadbalancing:DeregisterTargets",
              + "elasticloadbalancing:DescribeListenerCertificates",
              + "elasticloadbalancing:DescribeListeners",
              + "elasticloadbalancing:DescribeLoadBalancerAttributes",
              + "elasticloadbalancing:DescribeLoadBalancers",
              + "elasticloadbalancing:DescribeRules",
              + "elasticloadbalancing:DescribeSSLPolicies",
              + "elasticloadbalancing:DescribeTags",
              + "elasticloadbalancing:DescribeTargetGroupAttributes",
              + "elasticloadbalancing:DescribeTargetGroups",
              + "elasticloadbalancing:DescribeTargetHealth",
              + "elasticloadbalancing:ModifyListener",
              + "elasticloadbalancing:ModifyLoadBalancerAttributes",
              + "elasticloadbalancing:ModifyRule",
              + "elasticloadbalancing:ModifyTargetGroup",
              + "elasticloadbalancing:ModifyTargetGroupAttributes",
              + "elasticloadbalancing:RegisterTargets",
              + "elasticloadbalancing:RemoveListenerCertificates",
              + "elasticloadbalancing:RemoveTags",
              + "elasticloadbalancing:SetIpAddressType",
              + "elasticloadbalancing:SetSecurityGroups",
              + "elasticloadbalancing:SetSubnets",
              + "elasticloadbalancing:SetWebACL",
            ]
          + effect    = "Allow"
          + resources = [
              + "*",
            ]
        }
      + statement {
          + actions   = [
              + "iam:CreateServiceLinkedRole",
              + "iam:GetServerCertificate",
              + "iam:ListServerCertificates",
            ]
          + effect    = "Allow"
          + resources = [
              + "*",
            ]
        }
      + statement {
          + actions   = [
              + "waf-regional:AssociateWebACL",
              + "waf-regional:DisassociateWebACL",
              + "waf-regional:GetWebACL",
              + "waf-regional:GetWebACLForResource",
            ]
          + effect    = "Allow"
          + resources = [
              + "*",
            ]
        }
      + statement {
          + actions   = [
              + "tag:GetResources",
              + "tag:TagResources",
            ]
          + effect    = "Allow"
          + resources = [
              + "*",
            ]
        }
      + statement {
          + actions   = [
              + "waf:GetWebACL",
            ]
          + effect    = "Allow"
          + resources = [
              + "*",
            ]
        }
    }

  # module.eksalbingress.data.aws_iam_policy_document.alb_ingress_assume[0] will be read during apply
  # (config refers to values not yet known)
 <= data "aws_iam_policy_document" "alb_ingress_assume"  {
      + id   = (known after apply)
      + json = (known after apply)

      + statement {
          + actions = [
              + "sts:AssumeRoleWithWebIdentity",
            ]
          + effect  = "Allow"

          + condition {
              + test     = "StringEquals"
              + values   = [
                  + "system:serviceaccount:alb-ingress:aws-alb-ingress-controller",
                ]
              + variable = "oidc.eks.us-east-2.amazonaws.com/id/myid:sub"
            }

          + principals {
              + identifiers = [
                  + "arn:aws:iam::myaccount:oidc-provider/oidc.eks.us-east-2.amazonaws.com/id/myid",
                ]
              + type        = "Federated"
            }
        }
    }

  # module.eksalbingress.aws_iam_policy.alb_ingress[0] will be updated in-place
  ~ resource "aws_iam_policy" "alb_ingress" {
        arn         = "arn:aws:iam::myaccount:policy/mycluster-alb-ingress"
        description = "Policy for alb-ingress service"
        id          = "arn:aws:iam::myaccount:policy/mycluster-alb-ingress"
        name        = "mycluster-alb-ingress"
        path        = "/"
      ~ policy      = jsonencode(
            {
              - Statement = [
                  - {
                      - Action   = [
                          - "acm:ListCertificates",
                          - "acm:GetCertificate",
                          - "acm:DescribeCertificate",
                        ]
                      - Effect   = "Allow"
                      - Resource = "*"
                      - Sid      = ""
                    },
                  - {
                      - Action   = [
                          - "ec2:RevokeSecurityGroupIngress",
                          - "ec2:ModifyNetworkInterfaceAttribute",
                          - "ec2:ModifyInstanceAttribute",
                          - "ec2:DescribeVpcs",
                          - "ec2:DescribeTags",
                          - "ec2:DescribeSubnets",
                          - "ec2:DescribeSecurityGroups",
                          - "ec2:DescribeNetworkInterfaces",
                          - "ec2:DescribeInternetGateways",
                          - "ec2:DescribeInstances",
                          - "ec2:DescribeInstanceStatus",
                          - "ec2:DescribeAddresses",
                          - "ec2:DescribeAccountAttributes",
                          - "ec2:DeleteTags",
                          - "ec2:DeleteSecurityGroup",
                          - "ec2:CreateTags",
                          - "ec2:CreateSecurityGroup",
                          - "ec2:AuthorizeSecurityGroupIngress",
                        ]
                      - Effect   = "Allow"
                      - Resource = "*"
                      - Sid      = ""
                    },
                  - {
                      - Action   = [
                          - "elasticloadbalancing:SetWebACL",
                          - "elasticloadbalancing:SetSubnets",
                          - "elasticloadbalancing:SetSecurityGroups",
                          - "elasticloadbalancing:SetIpAddressType",
                          - "elasticloadbalancing:RemoveTags",
                          - "elasticloadbalancing:RemoveListenerCertificates",
                          - "elasticloadbalancing:RegisterTargets",
                          - "elasticloadbalancing:ModifyTargetGroupAttributes",
                          - "elasticloadbalancing:ModifyTargetGroup",
                          - "elasticloadbalancing:ModifyRule",
                          - "elasticloadbalancing:ModifyLoadBalancerAttributes",
                          - "elasticloadbalancing:ModifyListener",
                          - "elasticloadbalancing:DescribeTargetHealth",
                          - "elasticloadbalancing:DescribeTargetGroups",
                          - "elasticloadbalancing:DescribeTargetGroupAttributes",
                          - "elasticloadbalancing:DescribeTags",
                          - "elasticloadbalancing:DescribeSSLPolicies",
                          - "elasticloadbalancing:DescribeRules",
                          - "elasticloadbalancing:DescribeLoadBalancers",
                          - "elasticloadbalancing:DescribeLoadBalancerAttributes",
                          - "elasticloadbalancing:DescribeListeners",
                          - "elasticloadbalancing:DescribeListenerCertificates",
                          - "elasticloadbalancing:DeregisterTargets",
                          - "elasticloadbalancing:DeleteTargetGroup",
                          - "elasticloadbalancing:DeleteRule",
                          - "elasticloadbalancing:DeleteLoadBalancer",
                          - "elasticloadbalancing:DeleteListener",
                          - "elasticloadbalancing:CreateTargetGroup",
                          - "elasticloadbalancing:CreateRule",
                          - "elasticloadbalancing:CreateLoadBalancer",
                          - "elasticloadbalancing:CreateListener",
                          - "elasticloadbalancing:AddTags",
                          - "elasticloadbalancing:AddListenerCertificates",
                        ]
                      - Effect   = "Allow"
                      - Resource = "*"
                      - Sid      = ""
                    },
                  - {
                      - Action   = [
                          - "iam:ListServerCertificates",
                          - "iam:GetServerCertificate",
                          - "iam:CreateServiceLinkedRole",
                        ]
                      - Effect   = "Allow"
                      - Resource = "*"
                      - Sid      = ""
                    },
                  - {
                      - Action   = [
                          - "waf-regional:GetWebACLForResource",
                          - "waf-regional:GetWebACL",
                          - "waf-regional:DisassociateWebACL",
                          - "waf-regional:AssociateWebACL",
                        ]
                      - Effect   = "Allow"
                      - Resource = "*"
                      - Sid      = ""
                    },
                  - {
                      - Action   = [
                          - "tag:TagResources",
                          - "tag:GetResources",
                        ]
                      - Effect   = "Allow"
                      - Resource = "*"
                      - Sid      = ""
                    },
                  - {
                      - Action   = "waf:GetWebACL"
                      - Effect   = "Allow"
                      - Resource = "*"
                      - Sid      = ""
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> (known after apply)
    }

  # module.eksalbingress.aws_iam_role.alb_ingress[0] will be updated in-place
  ~ resource "aws_iam_role" "alb_ingress" {
        arn                   = "arn:aws:iam::myaccount:role/mycluster-alb-ingress"
      ~ assume_role_policy    = jsonencode(
            {
              - Statement = [
                  - {
                      - Action    = "sts:AssumeRoleWithWebIdentity"
                      - Condition = {
                          - StringEquals = {
                              - oidc.eks.us-east-2.amazonaws.com/id/myid:sub = "system:serviceaccount:alb-ingress:aws-alb-ingress-controller"
                            }
                        }
                      - Effect    = "Allow"
                      - Principal = {
                          - Federated = "arn:aws:iam::myaccount:oidc-provider/oidc.eks.us-east-2.amazonaws.com/id/myid"
                        }
                      - Sid       = ""
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> (known after apply)
        create_date           = "2020-07-19T20:53:30Z"
        force_detach_policies = false
        id                    = "mycluster-alb-ingress"
        max_session_duration  = 3600
        name                  = "mycluster-alb-ingress"
        path                  = "/"
        tags                  = {}
        unique_id             = "AROA2HABLYGXHBVVGYOAQ"
    }

Plan: 0 to add, 2 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if

```

**Comment by ismailyenigul** [comment]
i cancelled `terraform apply` and run it with auto-approve deploy again
but then it says 
`Apply complete! Resources: 0 added, 0 changed, 0 destroyed.`


```

Plan: 0 to add, 2 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: 
Apply cancelled.
$
 terraform apply -auto-approve 
module.vpc.module.label.data.null_data_source.tags_as_list_of_maps[1]: Refreshing state...
module.vpc.module.label.data.null_data_source.tags_as_list_of_maps[4]: Refreshing state...
module.vpc.module.label.data.null_data_source.tags_as_list_of_maps[0]: Refreshing state...
...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

```

If I run terraform apply again in 2 min later I got the same change in terraform apply


```

               }
                      - Sid       = ""
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> (known after apply)
        create_date           = "2020-07-19T20:53:30Z"
        force_detach_policies = false
        id                    = "mycluster-alb-ingress"
        max_session_duration  = 3600
        name                  = "mycuster-alb-ingress"
        path                  = "/"
        tags                  = {}
        unique_id             = "AROA2HABLYGXHBVVGYOAQ"
    }

Plan: 0 to add, 2 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.
```

I said yes but it did not change anything :D
```

  Enter a value: yes 

module.eksalbingress.data.aws_iam_policy_document.alb_ingress_assume[0]: Refreshing state...
module.eksalbingress.data.aws_iam_policy_document.alb_ingress[0]: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```


why does terraform reports this fake change?
